# Generated by Django 4.2 on 2023-05-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='endereco_cliente',
        ),
    ]
