# Generated by Django 4.2 on 2023-05-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_delete_endereco_conta_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='conta_ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='conta',
            name='saldo',
            field=models.IntegerField(default=0),
        ),
    ]
