# Generated by Django 4.2.1 on 2023-05-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_alter_user_bairro_alter_user_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='nome',
            field=models.CharField(default='FORDONE CARD', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartao',
            name='data_vencimento',
            field=models.CharField(default='10/2031', max_length=10),
            preserve_default=False,
        ),
    ]
