# Generated by Django 4.2 on 2023-05-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0007_alter_conta_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chaveTransferencia',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf_cnpj',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
