# Generated by Django 4.2 on 2023-05-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0009_remove_user_chavetransferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='saldo',
            field=models.IntegerField(default=4946),
        ),
    ]
