# Generated by Django 4.2 on 2023-05-30 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0011_alter_conta_saldo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='numero_parcela',
            new_name='num_parcelas',
        ),
        migrations.RenameField(
            model_name='emprestimo',
            old_name='juros',
            new_name='porcentagem_juros',
        ),
        migrations.RemoveField(
            model_name='cartao',
            name='data_vencimento',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='data_solicitacao',
        ),
        migrations.AddField(
            model_name='cartao',
            name='data_vencimento_ano',
            field=models.CharField(default=32, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartao',
            name='data_vencimento_mes',
            field=models.CharField(default=12, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='quantidade_parcelas',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conta',
            name='saldo',
            field=models.IntegerField(default=2480),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_aprovacao',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Extrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimentacao', models.DateField()),
                ('codigo_conta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contas.conta')),
            ],
        ),
    ]
