# Generated by Django 4.2 on 2023-05-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0012_rename_numero_parcela_emprestimo_num_parcelas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='texto',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conta',
            name='saldo',
            field=models.IntegerField(default=2767),
        ),
    ]
