# Generated by Django 4.2 on 2023-05-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0013_movimentacao_texto_alter_conta_saldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='data_hora',
        ),
        migrations.AlterField(
            model_name='conta',
            name='saldo',
            field=models.IntegerField(default=2944),
        ),
    ]
