# Generated by Django 4.2 on 2023-05-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0014_remove_movimentacao_data_hora_alter_conta_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='data_hora',
            field=models.CharField(default='31/05/2023 13:50', max_length=20),
        ),
        migrations.AlterField(
            model_name='conta',
            name='saldo',
            field=models.IntegerField(default=4166),
        ),
    ]
