# Generated by Django 4.2 on 2023-06-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0015_movimentacao_data_hora_alter_conta_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='saldo',
            field=models.IntegerField(default=1478),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data_hora',
            field=models.CharField(default='02/06/2023 15:42', max_length=20),
        ),
    ]
