# Generated by Django 4.2 on 2023-06-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0017_alter_conta_saldo_alter_movimentacao_data_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='saldo',
            field=models.IntegerField(default=2963),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data_hora',
            field=models.CharField(default='04/06/2023 16:57', max_length=20),
        ),
    ]
