# Generated by Django 4.2 on 2023-06-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0018_alter_conta_saldo_alter_movimentacao_data_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='saldo',
            field=models.IntegerField(default=1620),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data_hora',
            field=models.CharField(default='05/06/2023 13:04', max_length=20),
        ),
    ]
